import { Tilt_Warp } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const tiltWarp = Tilt_Warp({
    subsets: ['latin'],
    variable: '--font-tilt-warp',
});

const satoshi = localFont({
    src: [
        {
            path: '../../public/fonts/Satoshi-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/Satoshi-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../../public/fonts/Satoshi-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-satoshi',
});

export const metadata = {
    title: 'Softvence Frontend Task',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${satoshi.variable} ${tiltWarp.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col max-w-[1560px] mx-auto">
                {children}
            </body>
        </html>
    );
}
